FLine <- readLines("household_power_consumption.txt")
PatReg <- grep("[12]/2/2007",substr(FLine,1,8))
DataTable <- read.table(text=FLine[PatReg], header = TRUE,sep = ";", col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))

cols = c(3:9)    
DataTable[,cols] = apply(DataTable[,cols], 2, function(x) as.numeric(as.character(x)))
DataTable$DateTime <- strptime(paste(DataTable$Date, DataTable$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
png(filename='plot1.png',width=480,height=480,units='px')
hist(DataTable$Global_active_power,freq = TRUE, main = "Global Active Power", xlab = "Global Active Power (kilowatts)",col = "red")
dev.off()